import type { Config } from 'tailwindcss';
import { PluginAPI } from 'tailwindcss/types/config';

export default {
	darkMode: ['class'],
	content: [
		'./src/**/*.{js,ts,jsx,tsx}',
		'./src/pages/**/*.{js,ts,jsx,tsx,mdx}',
		'./src/components/**/*.{js,ts,jsx,tsx,mdx}',
		'./src/app/**/*.{js,ts,jsx,tsx,mdx}',
	],
	theme: {
		extend: {
			fontFamily: {
				inter: ['var(--font-inter)'],
				rubik: ['var(--font-rubik)'],
			},
			colors: {
				'main-blue': '#263D51',
				bg: '#F6F6F6',
				'snow-gray': '#EFEFEF',
				'sky-blue': '#4277B9',
				gray: '#ADADAD',
				'soft-white': '#fbfbfb',
				red: '#CC4B4D',
				'light-green': '#BFD27B',
				'gray-blue': '#3D5D70',
				'dark-gray': '#383838',
				'mid-gray': '#757575',
				'slate-night': '#101828',
				'hover-snow-gray': '#F5F5F5',
				'hover-sky-blue': '#6FA3D4',
				'hover-main-blue': '#4A657E',
				'hover-red': '#D84A47',
				'hover-gray': '#C4C4C4',
				'active-green': '#9DB750',
				'green-stats': '#A7CF3F',
				'red-stats': '#A12017',
				'purple-stats': '#674F8C',
				'orange-stats': '#E48948',
				// 'background-onboarding': '#A6C4EA33',
				// 'background-proshop': '#EEF2F7',
				// 'input-stripe': '#EOEOEO',
				// 'dark-yellow': '#D3A80F',
				// 'font-green': '#ACDB32',
				'green-two': '#A7CF3F',
				// 'jet-black': '#1C1C1C',
				// 'shareable-yellow': '#D7AE1D',
				//green: '#35C658',
				'light-red': '#FF4B4B80',
				black: '#000000',
				golden: '#F7CF70',
				green: '#9DB750',
				white: '#ffffff',
				background: 'hsl(var(--background))',
				foreground: 'hsl(var(--foreground))',
				card: {
					DEFAULT: 'hsl(var(--card))',
					foreground: 'hsl(var(--card-foreground))',
				},
				popover: {
					DEFAULT: 'hsl(var(--popover))',
					foreground: 'hsl(var(--popover-foreground))',
				},
				primary: {
					DEFAULT: 'hsl(var(--primary))',
					foreground: 'hsl(var(--primary-foreground))',
				},
				secondary: {
					DEFAULT: 'hsl(var(--secondary))',
					foreground: 'hsl(var(--secondary-foreground))',
				},
				muted: {
					DEFAULT: 'hsl(var(--muted))',
					foreground: 'hsl(var(--muted-foreground))',
				},
				accent: {
					DEFAULT: 'hsl(var(--accent))',
					foreground: 'hsl(var(--accent-foreground))',
				},
				destructive: {
					DEFAULT: 'hsl(var(--destructive))',
					foreground: 'hsl(var(--destructive-foreground))',
				},
				border: 'hsl(var(--border))',
				input: 'hsl(var(--input))',
				ring: 'hsl(var(--ring))',
				chart: {
					'1': 'hsl(var(--chart-1))',
					'2': 'hsl(var(--chart-2))',
					'3': 'hsl(var(--chart-3))',
					'4': 'hsl(var(--chart-4))',
					'5': 'hsl(var(--chart-5))',
				},
				sidebar: {
					DEFAULT: 'hsl(var(--sidebar-background))',
					foreground: 'hsl(var(--sidebar-foreground))',
					primary: 'hsl(var(--sidebar-primary))',
					'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
					accent: 'hsl(var(--sidebar-accent))',
					'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
					border: 'hsl(var(--sidebar-border))',
					ring: 'hsl(var(--sidebar-ring))',
				},
			},
			fontSize: {
				'rubik-70': '70px',
				'rubik-38': '38px',
				'rubik-32': '32px',
				'rubik-22': '22px',
				'rubik-18': '18px',
				'rubik-16': '16px',
				'rubik-14': '14px',
				'inter-medium-22': '22px',
				'inter-medium-20': '20px',
				'inter-medium-18': '18px',
				'inter-medium-16': '16px',
				'inter-medium-14': '14px',
				'inter-medium-12': '12px',
				'inter-18': '18px',
				'inter-16': '16px',
				'inter-14': '14px',
			},
			borderRadius: {
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 2px)',
				sm: 'calc(var(--radius) - 4px)',
			},
		},
	},
	plugins: [
		require('tailwindcss-animate'),
		function ({ addComponents }: PluginAPI) {
			addComponents({
				'.H1': {
					fontFamily: 'var(--font-rubik)',
					fontWeight: '500',
					lineHeight: '120%',
					letterSpacing: '-1px',
					fontSize: '22px',
				},
				'.H2': {
					fontFamily: 'var(--font-rubik)',
					fontWeight: '500',
					lineHeight: '120%',
					letterSpacing: '0',
					fontSize: '18px',
				},
				'.H3': {
					fontFamily: 'var(--font-rubik)',
					fontWeight: '500',
					lineHeight: '120%',
					letterSpacing: '0',
					fontSize: '16px',
				},
				'.Sub-H1': {
					fontFamily: 'var(--font-inter)',
					fontWeight: '500',
					lineHeight: '120%',
					letterSpacing: '-0.5px',
					fontSize: '22px',
				},
				'.Sub-H2': {
					fontFamily: 'var(--font-inter)',
					fontWeight: '500',
					lineHeight: '120%',
					letterSpacing: '-0.5px',
					fontSize: '18px',
				},
				'.Sub-H3': {
					fontFamily: 'var(--font-inter)',
					fontWeight: '500',
					lineHeight: '120%',
					letterSpacing: '-0.5px',
					fontSize: '16px',
				},
				'.Body-1': {
					fontFamily: 'var(--font-inter)',
					fontWeight: '400',
					letterSpacing: '0',
					lineHeight: '150%',
					fontSize: '18px',
				},
				'.Body-2': {
					fontFamily: 'var(--font-inter)',
					fontWeight: '400',
					letterSpacing: '0',
					lineHeight: '150%',
					fontSize: '16px',
				},
				'.Body-3': {
					fontFamily: 'var(--font-inter)',
					fontWeight: '400',
					letterSpacing: '0',
					lineHeight: '120%',
					fontSize: '14px',
				},
				'.Button': {
					fontFamily: 'var(--font-inter)',
					fontWeight: '500',
					letterSpacing: '0',
					lineHeight: '120%',
					fontSize: '18px',
				},
				'.Button-Small': {
					fontFamily: 'var(--font-inter)',
					fontWeight: '500',
					letterSpacing: '0',
					lineHeight: '120%',
					fontSize: '16px',
				},
				'.Caption': {
					fontFamily: 'var(--font-inter)',
					fontWeight: '500',
					letterSpacing: '0',
					lineHeight: '120%',
					fontSize: '14px',
				},
				'.Tag': {
					fontFamily: 'var(--font-inter)',
					fontWeight: '500',
					letterSpacing: '0',
					lineHeight: '120%',
					fontSize: '12px',
				},
				'.Numbers-Big': {
					fontFamily: 'var(--font-rubik)',
					fontWeight: '500',
					letterSpacing: '0',
					lineHeight: '120%',
					fontSize: '22px',
				},
				'.Numbers-Medium': {
					fontFamily: 'var(--font-rubik)',
					fontWeight: '500',
					letterSpacing: '0',
					lineHeight: '120%',
					fontSize: '18px',
				},
				'.Numbers-Small': {
					fontFamily: 'var(--font-rubik)',
					fontWeight: '500',
					letterSpacing: '0',
					lineHeight: '120%',
					fontSize: '14px',
				},
				'.D1': {
					fontFamily: 'var(--font-rubik)',
					fontWeight: '500',
					letterSpacing: '-1px',
					lineHeight: '150%',
					fontSize: '38px',
				},
				'.D2': {
					fontFamily: 'var(--font-rubik)',
					fontWeight: '500',
					letterSpacing: '-1px',
					lineHeight: '150%',
					fontSize: '14px',
				},
				'.S1': {
					fontFamily: 'var(--font-rubik)',
					fontWeight: '500',
					letterSpacing: '0px',
					lineHeight: '150%',
					fontSize: '32px',
				},
				'.S-Big': {
					fontFamily: 'var(--font-rubik)',
					fontWeight: '500',
					letterSpacing: '0px',
					lineHeight: '120%',
					fontSize: '70px',
				},
				'.B-Big': {
					fontFamily: 'var(--font-inter)',
					fontWeight: '500',
					letterSpacing: '0px',
					lineHeight: '120%',
					fontSize: '20px',
				},
			});
		},
	],
} satisfies Config;
